# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39f63a24864e776d59dcea70a88243cecb87980b73f4c48ea76bc87d41ceb04bbd388722f451e0131bf0ff6d750de052e786768e2c7f6c8c2b127da784127752

test:
  secret_key_base: 0518591cbb172977a03958222e2a6e4dec89a554ecc86b814fc5c231b211ad380419c88e430c66f711a9ebdc8ea43b52c51a3dc210abb3ef8a53e2bf7e265975

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
